services:
  web:
    image: nguyenhuutan080603044/e-exam-frontend:latest
    container_name: eexam_web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3003
    command: npm run dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  api:
    image: nguyenhuutan080603044/e-exam-backend:latest
    container_name: eexam_api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3003:3003"
    environment:
      NODE_ENV: production
      PORT: 3003
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/eexam"
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eexam
      POSTGRES_PORT: 5432
      CORS_ORIGINS: "http://localhost:3000"
    command: ["node", "dist/main"]
    restart: unless-stopped

  db:
    image: postgres:17
    container_name: eexam_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=eexam
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
    driver: local
